### ISSUE TITLE
Message text is cropped at the base of the screen with resolutions above 1080px high

### ISSUE THREAD

**Issue by kael131** [andrews05/EV-Nova-patches#4]
![image](https://github.com/andrews05/EV-Nova-CE/assets/38255868/4cecbe56-dc3f-4e33-9214-a88295c6e814)
When at higher resolution settings than 1080px high, I notice that comms message text that displays at the bottom is cropped.

**Comment by andrews05** [comment]
Hi @kael131, thanks for the report.

What resolution are you using? Have you enabled ui scaling, and if so what value?
I notice the text seems to be anti-aliased, which is unexpected as it should default to off at that size, unless you've changed the anti-aliasing setting. So it could mean ddraw.dll isn't installed or isn't working for some reason.

**Comment by andrews05** [comment]
This is now fixed in the latest release :)
