### ISSUE TITLE
Map borders not scaling properly on high UI scale

### ISSUE THREAD

**Issue by lieronet** [andrews05/EV-Nova-patches#5]
2.0 UI scale
![image](https://github.com/andrews05/EV-Nova-CE/assets/28401732/2cb2163d-d333-41b3-a11b-50f2c5710eaa)
1.3 UI scale
![image](https://github.com/andrews05/EV-Nova-CE/assets/28401732/1ec1e82d-fdb9-4c3d-b3ba-19d121c2cac2)
Default UI scale
![image](https://github.com/andrews05/EV-Nova-CE/assets/28401732/c9f318eb-45f4-4bc0-b84c-6f023068716f)

Guessing this is a known issue won't fix, but figured I'd raise it here all the same.

**Comment by andrews05** [comment]
Hi @lieronet
You're correct, this is a known issue. I won't say "won't fix" but it's unfortunately a rather complex one to solve and I'm not sure if it's worth the time and effort to get it to work. I'll leave the issue open, but it's unlikely to happen I'm afraid 🫤

**Comment by andrews05** [comment]
This is now resolved in r4 🥳
