### ISSUE TITLE
double hook 004CF7C3

### ISSUE THREAD

**Issue by FunkyFr3sh** [andrews05/EV-Nova-patches#6]
Just added a new feature to petool that scans for empty and conflicting patches and it found this:

> Warning: Conflicting patches: '004CF7C3 (5 bytes)' / '004CF7C3 (5 bytes)'
> Warning: Empty patch: '0045D287 (0 bytes)'
> Warning: Empty patch: '0045EA66 (0 bytes)'
> Warning: Empty patch: '0045EBE8 (0 bytes)'
> Warning: Empty patch: '0045F086 (0 bytes)'
> Warning: Empty patch: '00487FCD (0 bytes)'

```
CALL(0x004CF7C3, _parseDLOG);
CALL(0x004CF7C3, _parseDlogScaled);
```

**Comment by andrews05** [comment]
That sounds useful!

The parseDLOG is indeed redundant. I left it there in case there was ever a need to disable the scale patch, but I guess I should just comment it out.

The others I’m confused about, they seem to just be the end address of some hooks?

**Comment by FunkyFr3sh** [comment]
It's actually working right now so it's not a big deal. But if you would change the order of the files in the makefile then it would break because the _parseDLOG then would overwrite _parseDlogScaled (_parseDLOG  lacks scale code).

The other ones just warn about using the wrong HOOK macro, you used the one with 2 args that clears but there wasn't any need to clear

**Comment by andrews05** [comment]
Yes, I made sure to order them correctly 😉

Oh right, because they’re only 5 bytes long. I realise the second argument is redundant in that case, I just felt it was better (e.g. for readability) to be explicit about where the end is.

**Comment by andrews05** [comment]
I've disabled the older parseDLOG patch. The others I'm happy to stay as they are.
