### ISSUE TITLE
Lutris error

### ISSUE THREAD

**Issue by cryptoquick** [andrews05/EV-Nova-patches#7]
I've tried running with this Wine configuration in Lutris on Arch Linux:

![Screenshot from 2024-07-23 08-15-04](https://github.com/user-attachments/assets/7ad8e703-c237-4b67-805d-8e403886046e)

Unfortunately, I keep getting this error:

![Screenshot from 2024-07-23 07-51-05](https://github.com/user-attachments/assets/5b53c4fe-2df1-4417-bd4a-0e1d16387a26)

**Comment by FunkyFr3sh** [comment]
you need to add a dll override for "ddraw"

**Comment by cryptoquick** [comment]
That worked, thank you!

![Screenshot from 2024-07-23 14-13-59](https://github.com/user-attachments/assets/3c7f581b-446f-4521-a0ec-29f40d164954)

**Comment by andrews05** [comment]
Nice to see it's working for you!
I've just added a little hack that @FunkyFr3sh came up with to make the game automatically set the dll override when running in wine. So in a future release, you won't need to do this manually.

**Comment by cryptoquick** [comment]
That's awesome! Glad it'll be a good experience in the future. But there will always be Those Who Came Before...
