### ISSUE TITLE
Using keyboard navigation to buy and sell from trading center causes crashes

### ISSUE THREAD

**Issue by foxfirecodes** [andrews05/EV-Nova-patches#9]
so this is something i *think* i remember being a bug in the base game as well, but is also something that happened to me in both Windows & Linux so i know it's not just some Wine issue. when pressing alt+b or alt+s to buy or sell in bulk in the trade center, you can use tab or shift-tab to navigate to the buy/sell button and you're supposed to be able to then hit space to select the button, however instead it often causes the game to crash.

it doesn't happen every time and ive yet to figure out the exact repro steps. will add more to this issue if i can figure out what specific conditions cause it to happen, but it crashed me frequently enough during trading routes that i had to re-train my muscle memory to just use my mouse.

so just to clarify, the repro steps are:

1. ??? some condition ???
2. go to Trading Center
3. press <kbd>alt+b</kbd> to buy a specific quantity of one of the goods
4. press <kbd>tab</kbd> twice or <kbd>shift+tab</kbd> once in the resulting popup to highlight the "Buy" button
5. press <kbd>space</kbd> to activate the button

**Comment by foxfirecodes** [comment]
this damn game is gaslighting me, i swear, now its working perfectly even though it caused it to crash again right before i posted this issue. this is probably useless without a clear repro step so i'm just gonna close this and re-open later if/when i can figure out the exact conditions that cause it to crash

**Comment by andrews05** [comment]
Heisenbug! I haven't heard of this happening before. Do let me know if you find anything.

**Comment by andrews05** [comment]
FYI, I actually did manage to track this down. There's a hidden element in the dialog (and possibly others) that you can't see because it's positioned out of the frame but can tab to focus on. Triggering the hidden element with space will crash the game. It happens in the original (non-CE) version too. It's fairly obscure so I never bothered to try fixing it.
